apiVersion: apps/v1
kind: Deployment
metadata:
  name: aba-backend-api
  labels:
    app: aba-backend
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aba-backend
      component: api
  template:
    metadata:
      labels:
        app: aba-backend
        component: api
    spec:
      containers:
      - name: api
        image: aba-backend:latest
        ports:
        - containerPort: 4000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "4000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: aba-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: aba-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: aba-secrets
              key: jwt-secret
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: aba-secrets
              key: openai-api-key
        - name: WHATSAPP_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: aba-secrets
              key: whatsapp-api-token
        - name: MERCADOPAGO_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: aba-secrets
              key: mercadopago-access-token
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aba-backend-worker
  labels:
    app: aba-backend
    component: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aba-backend
      component: worker
  template:
    metadata:
      labels:
        app: aba-backend
        component: worker
    spec:
      containers:
      - name: worker
        image: aba-backend:latest
        command: ["npm", "run", "worker:prod"]
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: aba-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: aba-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: aba-secrets
              key: jwt-secret
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: aba-secrets
              key: openai-api-key
        - name: WHATSAPP_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: aba-secrets
              key: whatsapp-api-token
        - name: MERCADOPAGO_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: aba-secrets
              key: mercadopago-access-token
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: aba-backend-service
spec:
  selector:
    app: aba-backend
    component: api
  ports:
  - port: 80
    targetPort: 4000
  type: LoadBalancer

---
apiVersion: v1
kind: Secret
metadata:
  name: aba-secrets
type: Opaque
stringData:
  database-url: "postgresql://user:pass@postgres:5432/aba_db"
  redis-url: "redis://redis:6379/0"
  jwt-secret: "your-super-secret-jwt-key"
  openai-api-key: "sk-your-openai-key"
  whatsapp-api-token: "your-whatsapp-token"
  mercadopago-access-token: "your-mercadopago-token"
